### ISSUE TITLE
Kodi sync queue only working on startup

### ISSUE THREAD

**Issue by nanhoes** [jellyfin/jellyfin-plugin-kodisyncqueue#94] opened 2024-07-12 05:49 UTC
Hello,

For some reason kodi sync queue does not trigger automatically anymore. 

Jellyfin logs show the sync executing as normal but changes are not reflected in kodi until the app starts up.
 
Running jellyfin server `v10.9.5`, kodi jellyfin add on `v1.0.4`, and kodi-sync-queue `v11`

**Comment by mcarlton00** [comment] 2024-07-12 12:24
Kodi Sync Queue _only_ does something when Kodi first starts up.  This is how it's always worked.  Real time sync while Kodi is running by a websocket connection.  If that's not working, then something has caused that connection to drop and the reconnect attempts to also fail.

**Comment by nanhoes** [comment] 2024-07-13 19:03
Yes basically if I update metadata or import a new movie, changes are not reflected until next boot even when keeping Kodi on screen. Previously, changes were reflected within minutes.

**Comment by oddstr13** [comment] 2024-09-18 23:49
Based on your description, this plugin works as expected.

There seems to be an issue with jf4kodi's WebSocket connection to the server.
This *can* be caused by a miss-configured reverse proxy server.

Closing as this is not an issue with this plugin.

**Closed by oddstr13** 2024-09-18 23:49 UTC
